#Requires -Version 5.1
<#
.SYNOPSIS
  Helm 浏览器操作工具 —— 一键安装器
.DESCRIPTION
  非技术用户双击 install.bat 即可完成：
  1. 检测 Node.js / Chrome 环境
  2. 安装网关依赖
  3. 注册网关开机自启（Windows 计划任务 HelmGateway）
  4. 立即启动网关
  5. 自动加载 Chrome 扩展
  6. 验证连通并打印总结
#>

$ErrorActionPreference = 'Stop'
$PROJECT_ROOT = (Resolve-Path "$PSScriptRoot\..").Path
$GATEWAY_DIR  = Join-Path $PROJECT_ROOT 'gateway'
$EXTENSION_DIR = Join-Path $PROJECT_ROOT 'extension'
$DAEMON_SCRIPT = Join-Path $GATEWAY_DIR 'bridge-daemon.mjs'
$TASK_NAME = 'HelmGateway'
$GATEWAY_PORT = 8787
$STARTUP_DIR = Join-Path ([Environment]::GetFolderPath('ApplicationData')) 'Microsoft\Windows\Start Menu\Programs\Startup'
$VBS_NAME = 'HelmGateway.vbs'

# ---------- 辅助函数 ----------

function Write-Step($n, $total, $msg) {
    Write-Host "`n[$n/$total] $msg" -ForegroundColor Cyan
}

function Write-Ok($msg) {
    Write-Host "  [OK] $msg" -ForegroundColor Green
}

function Write-Warn($msg) {
    Write-Host "  [!] $msg" -ForegroundColor Yellow
}

function Write-Err($msg) {
    Write-Host "  [X] $msg" -ForegroundColor Red
}

function Write-Info($msg) {
    Write-Host "  $msg" -ForegroundColor DarkGray
}

# 退出码：0 成功，非零失败
function Abort($msg, $code = 1) {
    Write-Err $msg
    Write-Host "`n安装未完成。请按上述提示处理后重新运行 install.bat`n" -ForegroundColor Red
    exit $code
}

# ---------- Step 1: 环境检测 ----------

Write-Host "`n========================================" -ForegroundColor White
Write-Host "  Helm 安装器" -ForegroundColor White
Write-Host "========================================" -ForegroundColor White

Write-Step 1 6 '检测环境'

# --- Node.js ---
$nodeCmd = Get-Command node -ErrorAction SilentlyContinue
if (-not $nodeCmd) {
    Abort '未检测到 Node.js。请前往 https://nodejs.org 下载安装 LTS 版本后重试。'
}
$nodePath = $nodeCmd.Source
# 解析符号链接（nvm 的 nodejs 是 symlink，切版本后失效）
try {
    $nodeReal = (Get-Item $nodePath).Target
    if ($nodeReal) { $nodePath = $nodeReal }
} catch {}
# 再次 Resolve 确保是绝对真实路径
$nodePath = (Resolve-Path $nodePath).Path

$nodeVerRaw = & $nodePath --version 2>$null
$nodeVer = $nodeVerRaw -replace '^v', ''
$nodeMajor = [int]($nodeVer -split '\.')[0]
if ($nodeMajor -lt 18) {
    Abort "Node.js 版本过低 ($nodeVerRaw)，需要 18+。请升级后重试。"
}
Write-Ok "Node.js $nodeVer  ($nodePath)"

# 检测 nvm：路径含 \nvm\ 说明是 nvm 管理的版本，切版本后计划任务路径会失效
if ($nodePath -match '\\nvm\\') {
    Write-Warn "检测到 nvm 管理的 Node。切换 Node 版本后需重跑本安装器以更新启动项路径。"
}

# --- Chrome ---
$chromePath = $null
$chromeCandidates = @(
    "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe",
    "$env:ProgramFiles\Google\Chrome\Application\chrome.exe",
    "${env:ProgramFiles(x86)}\Google\Chrome\Application\chrome.exe"
)
foreach ($p in $chromeCandidates) {
    if (Test-Path $p) { $chromePath = $p; break }
}
if (-not $chromePath) {
    # 尝试注册表
    try {
        $reg = Get-ItemProperty 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe' -ErrorAction SilentlyContinue
        if ($reg.'(default)') { $chromePath = $reg.'(default)' }
    } catch {}
}
if (-not $chromePath) {
    Abort '未检测到 Google Chrome。请安装 Chrome 后重试。'
}
Write-Ok "Chrome  ($chromePath)"

# --- 项目路径 ---
if (-not (Test-Path $DAEMON_SCRIPT)) {
    Abort "未找到网关启动器: $DAEMON_SCRIPT"
}
Write-Ok "项目根  ($PROJECT_ROOT)"

# ---------- Step 2: 安装网关依赖 ----------

Write-Step 2 6 '安装网关依赖'

Push-Location $GATEWAY_DIR
try {
    $npmCmd = Get-Command npm -ErrorAction SilentlyContinue
    if (-not $npmCmd) {
        Abort '未检测到 npm。Node.js 安装可能不完整。'
    }
    Write-Info '运行 npm install...'
    & $npmCmd install --omit=dev 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Abort 'npm install 失败。请检查网络后重试。'
    }
    Write-Ok '依赖已安装'
} finally {
    Pop-Location
}

# ---------- Step 3: 注册开机自启（启动文件夹 + VBS 隐藏窗口）----------

Write-Step 3 6 '注册网关开机自启'

# 为什么不用计划任务（schtasks /SC ONLOGON）：ONLOGON 触发器需要管理员权限创建，
# 非管理员用户会"拒绝访问"。启动文件夹是用户级的，零权限即可，登录时自动执行。
# 用 VBS 启动而非直接放 .bat：VBS 的 Run(..., 0, False) 能隐藏黑色控制台窗口，
# 网关后台静默运行。

$startBat = Join-Path $GATEWAY_DIR 'start-gateway.bat'
$vbsPath = Join-Path $STARTUP_DIR $VBS_NAME

# VBS 内容：静默调用 start-gateway.bat（窗口模式 0 = 隐藏）
$vbsContent = @"
' HelmGateway auto-start (generated by installer)
' Silently start the gateway (hidden console window)
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run Chr(34) & "$startBat" & Chr(34), 0, False
"@

Set-Content -Path $vbsPath -Value $vbsContent -Encoding ASCII -Force
if (-not (Test-Path $vbsPath)) {
    Abort "写入启动项失败: $vbsPath"
}
Write-Ok "开机自启已注册 ($vbsPath)"

# ---------- Step 4: 立即启动网关 ----------

Write-Step 4 6 '启动网关'

# 若 8787 已有进程在监听（比如之前手动起的 bridge），先别重复起
$bridgeRunning = $false
try {
    $resp = Invoke-RestMethod "http://127.0.0.1:$GATEWAY_PORT/health" -TimeoutSec 2 -ErrorAction Stop
    if ($resp.ok) {
        $bridgeRunning = $true
        Write-Warn '网关已在运行（检测到已有进程），跳过启动'
    }
} catch {}

if (-not $bridgeRunning) {
    # 通过刚写入的 VBS 启动网关（静默，隐藏窗口）
    # 也可直接 Start-Process，但走 VBS 与开机自启行为一致
    $prevPref = $ErrorActionPreference
    $ErrorActionPreference = 'SilentlyContinue'
    Start-Process 'wscript.exe' "`"$vbsPath`""
    $ErrorActionPreference = $prevPref
    Write-Info '等待网关启动...'
    $ready = $false
    for ($i = 0; $i -lt 20; $i++) {
        Start-Sleep -Milliseconds 500
        try {
            $resp = Invoke-RestMethod "http://127.0.0.1:$GATEWAY_PORT/health" -TimeoutSec 2 -ErrorAction Stop
            if ($resp.ok) { $ready = $true; break }
        } catch {}
    }
    if (-not $ready) {
        Abort '网关启动失败。请手动运行: node bridge-daemon.mjs 检查报错。'
    }
    Write-Ok "网关已启动 (127.0.0.1:$GATEWAY_PORT)"
}

# ---------- Step 5: 加载 Chrome 扩展 ----------

Write-Step 5 6 '加载 Chrome 扩展'

# Chrome 的 --load-extension 参数在已有 profile 上不可靠（Chrome 150+ 会静默忽略），
# 且无法附加到已运行的 Chrome 实例。因此统一采用引导手动加载的方式。
# 安装器打开 chrome://extensions 页面，给出清晰步骤，用户 3 步完成。

Write-Info '请在 Chrome 中手动加载扩展（约 10 秒）：'
Write-Info ''
Write-Info '  1. 确认右上角"开发者模式"已开启（如未开启请先打开开关）'
Write-Info '  2. 点击"加载已解压的扩展程序"'
Write-Info "  3. 选择目录：$EXTENSION_DIR"
Write-Info ''
Write-Info '正在为你打开 Chrome 扩展管理页...'
Start-Process $chromePath 'chrome://extensions'

# 给 Chrome 几秒启动
Start-Sleep -Seconds 3

# ---------- Step 6: 验证连通 ----------

Write-Step 6 6 '验证连通'

Write-Info '等待扩展连接网关（最多 30s）...'
$extConnected = $false
for ($i = 0; $i -lt 30; $i++) {
    Start-Sleep -Seconds 1
    try {
        $resp = Invoke-RestMethod "http://127.0.0.1:$GATEWAY_PORT/health" -TimeoutSec 2 -ErrorAction Stop
        if ($resp.ext) { $extConnected = $true; break }
    } catch {}
}

# ---------- 总结 ----------

Write-Host "`n========================================" -ForegroundColor White
Write-Host "  安装结果" -ForegroundColor White
Write-Host "========================================" -ForegroundColor White

Write-Ok "Node.js $nodeVer"
Write-Ok "Chrome"
Write-Ok '网关依赖已安装'
Write-Ok '开机自启已注册 (启动文件夹)'
Write-Ok "网关已运行 (127.0.0.1:$GATEWAY_PORT)"

if ($extConnected) {
    Write-Ok '扩展已连接网关'
    Write-Host "`n全部完成！现在可以在 ZCode / Claude Desktop / Cursor 中使用 Helm 工具。`n" -ForegroundColor Green
} else {
    Write-Warn '扩展尚未连接网关'
    Write-Host "  请按上方 Step 5 的提示在 chrome://extensions 手动加载扩展。" -ForegroundColor Yellow
    Write-Host "  加载后 Side Panel 显示绿色"已连接网关"即成功。" -ForegroundColor Yellow
    Write-Host ""
}

Write-Host "卸载：双击 uninstall.bat`n" -ForegroundColor DarkGray

# ---------- Agent 接入配置（路径已按本机实际路径生成）----------

$mcpScript = "$GATEWAY_DIR\mcp-server.mjs"
# JSON 字符串中反斜杠需转义为双反斜杠：C:\path\to → C:\\path\\to
$mcpScriptEsc = $mcpScript.Replace('\', '\\')

Write-Host "========================================" -ForegroundColor White
Write-Host "  Agent 接入配置" -ForegroundColor White
Write-Host "========================================" -ForegroundColor White
Write-Host ""
Write-Host "  将以下配置添加到你的 Agent 配置文件中：" -ForegroundColor DarkGray
Write-Host "  （路径已按本机实际路径生成）`n" -ForegroundColor DarkGray

Write-Host "[ZCode] ~/.zcode/cli/config.json:" -ForegroundColor Cyan
Write-Host @"
{
  "mcp": {
    "servers": {
      "helm": {
        "type": "stdio",
        "command": "node",
        "args": ["$mcpScriptEsc"]
      }
    }
  }
}
"@
Write-Host ""

Write-Host "[Claude Code] .mcp.json 或 ~/.claude.json:" -ForegroundColor Cyan
Write-Host @"
{
  "mcpServers": {
    "helm": {
      "type": "stdio",
      "command": "node",
      "args": ["$mcpScriptEsc"]
    }
  }
}
"@
Write-Host ""

Write-Host "[Qwen CLI] ~/.qwen/settings.json:" -ForegroundColor Cyan
Write-Host @"
{
  "mcpServers": {
    "helm": {
      "command": "node",
      "args": ["$mcpScriptEsc"]
    }
  }
}
"@
Write-Host ""

Write-Host "[Hermes Agent] %LOCALAPPDATA%\hermes\config.yaml:" -ForegroundColor Cyan
Write-Host @"
mcp_servers:
  helm:
    command: "node"
    args: ["$mcpScript"]
"@
Write-Host ""

Write-Host "[Codex CLI] ~/.codex/config.toml:" -ForegroundColor Cyan
Write-Host @"
[mcp_servers.helm]
command = "node"
args = ["$mcpScript"]
"@
Write-Host ""

Write-Host "  注意：如用 nvm，command 可直接写 `"node`"（从 PATH 解析），" -ForegroundColor DarkGray
Write-Host "  避免硬编码 node.exe 路径导致切版本后失效。`n" -ForegroundColor DarkGray
exit 0
